mysql:
  image: mysql
  volumes:
    - /srv/lep/mysql:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: "superSecure"

helper:
  build: helper

api:
  build: api
  links:
    - mysql
  environment:
    DEVELOPMENT:       ${DEVELOPMENT}
    SENDGRID_API_KEY:  ${SENDGRID_API_KEY}
    JAWSDB_URL:        ${JAWSDB_URL}
    DEVEL_PRIVATE_KEY: ${DEVEL_PRIVATE_KEY}
    DEVEL_PUBLIC_KEY:  ${DEVEL_PUBLIC_KEY}
  volumes:
    # Static files are mounted as a volume.
    - ./:/srv

spa:
  build: spa
  ports:
    - 80:80
  links:
    - api
  volumes:
    # Static files are mounted as a volume.
    - ./:/usr/share/nginx/html
